---
 - hosts: all
   tasks:
    - name: ansible jinja2 if conditions
      debug: 
       msg:  --== Ansible Jinja2 if statement ==--
             {# If the hostname is ubuntu-c, include a message -#}
             {% if ansible_hostname == "ubuntu-c" -%}
                   This is ubuntu-c
             {% endif %}